name: dotnet publish binaries

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore
      - run: dotnet publish --os win
      - run: dotnet publish --os osx
      - run: dotnet publish --os linux

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uextract-win
          path: ./bin/Release/net8.0/win-x64/publish/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uextract-osx
          path: ./bin/Release/net8.0/osx-x64/publish/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uextract-linux
          path: ./bin/Release/net8.0/linux-x64/publish/
